# Generated by Django 5.0.1 on 2024-01-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='constact_no',
            new_name='contact_no',
        ),
    ]
